### ISSUE TITLE
Small issue from Reddit

### ISSUE THREAD

**Issue by ghost** [CDcruzCode/Quasai-GPT-Client#1]
From my own comment:

Cool stuff, one thing I noticed - you're using the wrong tokenizer for the `gpt-3.5-turbo` and `gpt-4` models. Seems like OpenAI wasn't clear enough in its documentation, so a lot of people get it wrong, but those models use a different tokenizer than the previous models. The new one is `cl100k_base`. Right now it's only available in https://github.com/openai/tiktoken and in its NodeJS port via WASM - https://www.npmjs.com/package/@dqbd/tiktoken

**Comment by ghost** [comment]
It should be quite trivial to fix it as it looks like your project already has code to convert the older tokenizer

**Comment by ghost** [comment]
@CDcruzCode replying to your Reddit comment so it doesn't get lost:

> The OpenAI website tokenizer https://platform.openai.com/tokenizer and my tokenizer produce the same token IDs.

That's true, it's because the tokenizer on their website only works for GPT-2, GPT-3 (base models like ada/curie/davinci), and all GPT-3.5 models (like text-davinci-003) excluding `gpt-3.5-turbo`. It does not work for `gpt-3.5-turbo` and `gpt-4`, I really do not understand why they still haven't added it. Also, due to how prompts are structured in the new models (via the messages array), there's some extra overhead for each message, resulting in about 6 tokens total per message - see https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb Section 6.

**Comment by CDcruzCode** [comment]
> That's true, it's because the tokenizer on their website only works for GPT-2, GPT-3 (base models like ada/curie/davinci), and all GPT-3.5 models (like text-davinci-003) excluding `gpt-3.5-turbo`. It does not work for `gpt-3.5-turbo` and `gpt-4`, I really do not understand why they still haven't added it. Also, due to how prompts are structured in the new models (via the messages array), there's some extra overhead for each message, resulting in about 6 tokens total per message - see https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb Section 6.

Thanks for this! I'll try updating my Tokenizer. Although It mainly just calls the C# script by Dluc.
I'll have to figure out how to implement titoken's script into Godot or port it over in some way.

**Comment by ghost** [comment]
@CDcruzCode I'll also give it a go since I'm quite interested in Godot 4 :) Although I'll first try reimplementing the basics in a different language (Nim) which I'm more accustomed with, just to see how hard it would be to make it work.

**Comment by CDcruzCode** [comment]
Thanks to a new C# library I found. https://github.com/dmitry-brazhenko/SharpToken the tokenizer tool now supports GPT 4 & GPT 3.5 tokenization and GPT 3 tokenization.
I haven't released the new version yet, but I'll close this issue. It will be resolved in the next update.
